// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: param.proto

#ifndef PROTOBUF_param_2eproto__INCLUDED
#define PROTOBUF_param_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace hityavie {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_param_2eproto();
void protobuf_AssignDesc_param_2eproto();
void protobuf_ShutdownFile_param_2eproto();

class ImuNoiseParameter;

// ===================================================================

class ImuNoiseParameter : public ::google::protobuf::Message {
 public:
  ImuNoiseParameter();
  virtual ~ImuNoiseParameter();

  ImuNoiseParameter(const ImuNoiseParameter& from);

  inline ImuNoiseParameter& operator=(const ImuNoiseParameter& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ImuNoiseParameter& default_instance();

  void Swap(ImuNoiseParameter* other);

  // implements Message ----------------------------------------------

  ImuNoiseParameter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ImuNoiseParameter& from);
  void MergeFrom(const ImuNoiseParameter& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double acc_noise = 1;
  inline bool has_acc_noise() const;
  inline void clear_acc_noise();
  static const int kAccNoiseFieldNumber = 1;
  inline double acc_noise() const;
  inline void set_acc_noise(double value);

  // required double gyr_noise = 2;
  inline bool has_gyr_noise() const;
  inline void clear_gyr_noise();
  static const int kGyrNoiseFieldNumber = 2;
  inline double gyr_noise() const;
  inline void set_gyr_noise(double value);

  // required double ba_noise = 3;
  inline bool has_ba_noise() const;
  inline void clear_ba_noise();
  static const int kBaNoiseFieldNumber = 3;
  inline double ba_noise() const;
  inline void set_ba_noise(double value);

  // required double bg_noise = 4;
  inline bool has_bg_noise() const;
  inline void clear_bg_noise();
  static const int kBgNoiseFieldNumber = 4;
  inline double bg_noise() const;
  inline void set_bg_noise(double value);

  // @@protoc_insertion_point(class_scope:hityavie.ImuNoiseParameter)
 private:
  inline void set_has_acc_noise();
  inline void clear_has_acc_noise();
  inline void set_has_gyr_noise();
  inline void clear_has_gyr_noise();
  inline void set_has_ba_noise();
  inline void clear_has_ba_noise();
  inline void set_has_bg_noise();
  inline void clear_has_bg_noise();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double acc_noise_;
  double gyr_noise_;
  double ba_noise_;
  double bg_noise_;
  friend void  protobuf_AddDesc_param_2eproto();
  friend void protobuf_AssignDesc_param_2eproto();
  friend void protobuf_ShutdownFile_param_2eproto();

  void InitAsDefaultInstance();
  static ImuNoiseParameter* default_instance_;
};
// ===================================================================


// ===================================================================

// ImuNoiseParameter

// required double acc_noise = 1;
inline bool ImuNoiseParameter::has_acc_noise() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ImuNoiseParameter::set_has_acc_noise() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ImuNoiseParameter::clear_has_acc_noise() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ImuNoiseParameter::clear_acc_noise() {
  acc_noise_ = 0;
  clear_has_acc_noise();
}
inline double ImuNoiseParameter::acc_noise() const {
  // @@protoc_insertion_point(field_get:hityavie.ImuNoiseParameter.acc_noise)
  return acc_noise_;
}
inline void ImuNoiseParameter::set_acc_noise(double value) {
  set_has_acc_noise();
  acc_noise_ = value;
  // @@protoc_insertion_point(field_set:hityavie.ImuNoiseParameter.acc_noise)
}

// required double gyr_noise = 2;
inline bool ImuNoiseParameter::has_gyr_noise() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ImuNoiseParameter::set_has_gyr_noise() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ImuNoiseParameter::clear_has_gyr_noise() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ImuNoiseParameter::clear_gyr_noise() {
  gyr_noise_ = 0;
  clear_has_gyr_noise();
}
inline double ImuNoiseParameter::gyr_noise() const {
  // @@protoc_insertion_point(field_get:hityavie.ImuNoiseParameter.gyr_noise)
  return gyr_noise_;
}
inline void ImuNoiseParameter::set_gyr_noise(double value) {
  set_has_gyr_noise();
  gyr_noise_ = value;
  // @@protoc_insertion_point(field_set:hityavie.ImuNoiseParameter.gyr_noise)
}

// required double ba_noise = 3;
inline bool ImuNoiseParameter::has_ba_noise() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ImuNoiseParameter::set_has_ba_noise() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ImuNoiseParameter::clear_has_ba_noise() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ImuNoiseParameter::clear_ba_noise() {
  ba_noise_ = 0;
  clear_has_ba_noise();
}
inline double ImuNoiseParameter::ba_noise() const {
  // @@protoc_insertion_point(field_get:hityavie.ImuNoiseParameter.ba_noise)
  return ba_noise_;
}
inline void ImuNoiseParameter::set_ba_noise(double value) {
  set_has_ba_noise();
  ba_noise_ = value;
  // @@protoc_insertion_point(field_set:hityavie.ImuNoiseParameter.ba_noise)
}

// required double bg_noise = 4;
inline bool ImuNoiseParameter::has_bg_noise() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ImuNoiseParameter::set_has_bg_noise() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ImuNoiseParameter::clear_has_bg_noise() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ImuNoiseParameter::clear_bg_noise() {
  bg_noise_ = 0;
  clear_has_bg_noise();
}
inline double ImuNoiseParameter::bg_noise() const {
  // @@protoc_insertion_point(field_get:hityavie.ImuNoiseParameter.bg_noise)
  return bg_noise_;
}
inline void ImuNoiseParameter::set_bg_noise(double value) {
  set_has_bg_noise();
  bg_noise_ = value;
  // @@protoc_insertion_point(field_set:hityavie.ImuNoiseParameter.bg_noise)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace hityavie

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_param_2eproto__INCLUDED
